#pragma once

// Single-page dashboard HTML, embedded as a C string literal.
// Served from GET / on the ESP32 webserver.
// Auto-refreshes status every 4 seconds via fetch(/api/status).
// WiFi STA configuration form posts to /api/wifi.

static const char DASHBOARD_HTML[] =
"<!DOCTYPE html>"
"<html lang='en'><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1'>"
"<title>ESP32S3-Base</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:system-ui,sans-serif;background:#0f172a;color:#e2e8f0;min-height:100vh}"
"header{background:#1e293b;padding:16px 24px;display:flex;align-items:center;gap:12px;border-bottom:1px solid #334155}"
"header h1{font-size:1.2rem;font-weight:700;color:#38bdf8}"
"header .sub{font-size:.8rem;color:#64748b}"
".badge{font-size:.65rem;padding:2px 8px;border-radius:999px;font-weight:600;text-transform:uppercase;letter-spacing:.05em}"
".badge.ok{background:#166534;color:#86efac}"
".badge.warn{background:#78350f;color:#fcd34d}"
".badge.err{background:#7f1d1d;color:#fca5a5}"
".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px;padding:20px}"
".card{background:#1e293b;border:1px solid #334155;border-radius:12px;padding:16px}"
".card h2{font-size:.85rem;text-transform:uppercase;letter-spacing:.1em;color:#64748b;margin-bottom:12px;display:flex;align-items:center;gap:8px}"
".row{display:flex;justify-content:space-between;align-items:center;padding:4px 0;border-bottom:1px solid #0f172a;font-size:.85rem}"
".row:last-child{border:none}"
".label{color:#94a3b8}"
".value{font-weight:600;color:#e2e8f0;text-align:right;max-width:55%}"
".stream-wrap{width:100%;margin-top:12px;border-radius:8px;overflow:hidden;background:#0f172a}"
".stream-wrap img{width:100%;display:block}"
"form.wifi-form{margin-top:12px;display:flex;flex-direction:column;gap:8px}"
"input[type=text],input[type=password]{"
"  background:#0f172a;border:1px solid #334155;border-radius:6px;"
"  padding:8px 10px;color:#e2e8f0;font-size:.85rem;width:100%"
"}"
"input:focus{outline:none;border-color:#38bdf8}"
".btn{padding:8px 14px;border-radius:6px;border:none;cursor:pointer;font-size:.82rem;font-weight:600}"
".btn-primary{background:#0284c7;color:#fff}"
".btn-danger{background:#dc2626;color:#fff}"
".btn-row{display:flex;gap:8px;margin-top:4px}"
"#wifi-msg{font-size:.8rem;margin-top:6px;min-height:1.2em}"
"#wifi-msg.ok{color:#86efac}#wifi-msg.err{color:#fca5a5}"
"</style></head><body>"

"<header>"
"  <div>"
"    <h1>ESP32S3-Base</h1>"
"    <div class='sub'>Waveshare ESP32-S3-SIM7670G-4G &mdash; debug dashboard</div>"
"  </div>"
"</header>"

"<div class='grid'>"

"<div class='card' style='grid-column:1/-1'>"
"  <h2>&#128247; Camera Stream</h2>"
"  <div class='stream-wrap'><img id='stream' src='/stream' alt='Camera stream'></div>"
"  <div style='margin-top:8px;display:flex;gap:8px;align-items:center'>"
"    <button class='btn btn-primary' onclick='toggleStream()' id='streamBtn'>Pause</button>"
"    <button class='btn' style='background:#334155;color:#e2e8f0' onclick=\"window.open('/snapshot','_blank')\">Snapshot</button>"
"    <span id='stream-status' style='font-size:.8rem;color:#64748b;margin-left:8px'>Live</span>"
"  </div>"
"</div>"

"<div class='card'>"
"  <h2>&#128225; WiFi <span id='wifi-badge' class='badge ok'>AP</span></h2>"
"  <div id='wifi-rows'></div>"
"  <hr style='border:none;border-top:1px solid #334155;margin:12px 0'>"
"  <div style='font-size:.8rem;color:#64748b;margin-bottom:6px'>Connect to a network</div>"
"  <form class='wifi-form' onsubmit='connectWifi(event)'>"
"    <input type='text' id='wifiSsid' placeholder='SSID' autocomplete='off'>"
"    <input type='password' id='wifiPass' placeholder='Password'>"
"    <div class='btn-row'>"
"      <button type='submit' class='btn btn-primary'>Connect</button>"
"      <button type='button' class='btn btn-danger' onclick='clearWifi()'>Disconnect</button>"
"    </div>"
"    <div id='wifi-msg'></div>"
"  </form>"
"</div>"

"<div class='card'>"
"  <h2>&#128246; 4G / SIM7670G <span id='sim-badge' class='badge warn'>...</span></h2>"
"  <div id='sim-rows'></div>"
"</div>"

"<div class='card'>"
"  <h2>&#128225; Bluetooth LE <span id='ble-badge' class='badge warn'>...</span></h2>"
"  <div id='ble-rows'></div>"
"</div>"

"<div class='card'>"
"  <h2>&#9881; System <span id='sys-badge' class='badge ok'>OK</span></h2>"
"  <div id='sys-rows'></div>"
"</div>"

"</div>"

"<script>"
// Escape HTML to prevent XSS from server-controlled field values
"function esc(v){"
"  if(v==null)return '-';"
"  return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');"
"}"

// Build a status row using safe escaped values
"function row(label,val){"
"  const d=document.createElement('div');d.className='row';"
"  const l=document.createElement('span');l.className='label';l.textContent=label;"
"  const v=document.createElement('span');v.className='value';v.textContent=String(val!=null?val:'-');"
"  d.appendChild(l);d.appendChild(v);return d;"
"}"

"function setBadge(id,text,cls){"
"  const e=document.getElementById(id);"
"  if(!e)return;e.textContent=text;e.className='badge '+cls;"
"}"

"function setRows(id,nodes){"
"  const e=document.getElementById(id);if(!e)return;"
"  e.innerHTML='';"
"  nodes.forEach(n=>e.appendChild(n));"
"}"

"let streamPaused=false;"
"function toggleStream(){"
"  const img=document.getElementById('stream');"
"  const btn=document.getElementById('streamBtn');"
"  const lbl=document.getElementById('stream-status');"
"  if(streamPaused){"
"    img.src='/stream?t='+Date.now();btn.textContent='Pause';lbl.textContent='Live';streamPaused=false;"
"  }else{"
"    img.src='';btn.textContent='Resume';lbl.textContent='Paused';streamPaused=true;"
"  }"
"}"

"function fmtUptime(s){"
"  const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),ss=s%60;"
"  return [h,m,ss].map(n=>String(n).padStart(2,'0')).join(':');"
"}"

"async function fetchStatus(){"
"  try{"
"    const r=await fetch('/api/status');"
"    if(!r.ok)return;"
"    const d=await r.json();"

"    const w=d.wifi||{};"
"    const wrows=[row('AP IP',w.ap_ip),row('AP clients',w.ap_clients??0)];"
"    if(w.sta_connected){"
"      wrows.push(row('STA network',w.sta_ssid));"
"      wrows.push(row('STA IP',w.sta_ip));"
"      wrows.push(row('STA signal',(w.sta_rssi?w.sta_rssi+' dBm':'-')));"
"      setBadge('wifi-badge','AP+STA','ok');"
"    }else{"
"      setBadge('wifi-badge','AP only','ok');"
"    }"
"    setRows('wifi-rows',wrows);"

"    const s=d.sim||{};"
"    const simOk=s.initialized&&s.registered;"
"    setBadge('sim-badge',simOk?'Online':'Offline',simOk?'ok':'warn');"
"    setRows('sim-rows',["
"      row('Initialized',s.initialized?'Yes':'No'),"
"      row('Registered',s.registered?'Yes':'No'),"
"      row('Signal',s.rssi_dbm?s.rssi_dbm+' dBm (CSQ '+s.csq+')':'-'),"
"      row('Operator',s.operator_name),"
"      row('4G IP',s.ip)"
"    ]);"

"    const b=d.ble||{};"
"    setBadge('ble-badge',b.advertising?'Advertising':'Idle',b.advertising?'ok':'warn');"
"    setRows('ble-rows',["
"      row('Device name',b.device_name),"
"      row('Advertising',b.advertising?'Yes':'No'),"
"      row('Connections',b.connections??0)"
"    ]);"

"    const sy=d.system||{};"
"    const heapPct=sy.total_heap?Math.round((sy.free_heap/sy.total_heap)*100):0;"
"    setRows('sys-rows',["
"      row('Uptime',sy.uptime_s!=null?fmtUptime(sy.uptime_s):'-'),"
"      row('Free heap',sy.free_heap!=null?sy.free_heap+' B ('+heapPct+'%)':'-'),"
"      row('Chip',sy.chip_model),"
"      row('SD card',sy.sd_mounted?'Mounted':'Not mounted'),"
"      row('SD free',sy.sd_mounted&&sy.sd_free_mb!=null?sy.sd_free_mb+' MB':'-')"
"    ]);"
"  }catch(e){console.warn('status error',e);}"
"}"

"async function connectWifi(ev){"
"  ev.preventDefault();"
"  const ssid=document.getElementById('wifiSsid').value.trim();"
"  const pass=document.getElementById('wifiPass').value;"
"  const msg=document.getElementById('wifi-msg');"
"  if(!ssid){msg.textContent='Enter an SSID';msg.className='err';return;}"
"  msg.textContent='Connecting...';msg.className='';"
"  try{"
"    const r=await fetch('/api/wifi',{"
"      method:'POST',"
"      headers:{'Content-Type':'application/json'},"
"      body:JSON.stringify({ssid,password:pass})"
"    });"
"    const d=await r.json();"
"    if(r.ok){msg.textContent='Connected: '+d.ip;msg.className='ok';"
"    }else{msg.textContent=d.error||'Failed';msg.className='err';}"
"  }catch(e){msg.textContent='Request failed';msg.className='err';}"
"}"

"async function clearWifi(){"
"  const msg=document.getElementById('wifi-msg');"
"  try{"
"    await fetch('/api/wifi',{method:'DELETE'});"
"    msg.textContent='Disconnected from STA';msg.className='ok';"
"  }catch(e){msg.textContent='Failed';msg.className='err';}"
"}"

"fetchStatus();setInterval(fetchStatus,4000);"
"</script>"
"</body></html>";
